server:
  port: 8091
spring:
  application:
    name: RabbitMq_project

rabbitmq:
  exchanges:
    notification: notification.exchange
  queues:
    notification: notification.queue
  routing-keys:
    notification: notification.routing-key